# Generated by Django 5.2.6 on 2025-09-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Име и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл адрес')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('delivery_method', models.CharField(choices=[('address', 'Доставка до адрес'), ('office', 'Доставка до офис/АПС')], default='address', max_length=16)),
                ('courier', models.CharField(choices=[('speedy', 'Спиди'), ('econt', 'Еконт')], default='speedy', max_length=16)),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Град')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='Пощенски код')),
                ('office_text', models.CharField(blank=True, max_length=255, verbose_name='Офис / АПС')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal_bgn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_bgn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bgn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Плащане с карта'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('cod', 'Наложен платеж')], max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('price_bgn', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (лв)')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (€)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_bgn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикули',
            },
        ),
    ]
