# Generated by Django 5.2.6 on 2025-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.CharField(choices=[('econt', 'Еконт')], default='econt', max_length=16),
        ),
    ]
