# Generated by Django 5.2.6 on 2025-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='econt_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='econt_labels/'),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_office_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_shipment_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
