# Generated by Django 5.2.6 on 2025-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_econt_errors_order_econt_label_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_apartment',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Фактура: Апартамент'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Фактура: Град'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Фактура: Имейл'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_entrance',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Фактура: Вход'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_floor',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Фактура: Етаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Фактура: Име и фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_num',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Фактура: №'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Фактура: Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Фактура: Пощ. код'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фактура: Улица/бул.'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_same_as_billing',
            field=models.BooleanField(default=True, verbose_name='Използвай фактурния адрес за доставка'),
        ),
    ]
