# Generated by Django 5.2.6 on 2025-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_billing_apartment_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Плащане с карта'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('cod', 'Наложен платеж')], default='card', max_length=20, verbose_name='Метод на плащане'),
        ),
    ]
