# Generated by Django 5.2.6 on 2026-10-01 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill(apps, schema_editor):
    """
    Neutral backfill of the new columns for EXISTING orders. Business data is not changed and nothing is flagged
    here (historical analysis is done read-only by `manage.py reconcile_orders`).
    """
    import uuid
    from django.db.models import F

    Order = apps.get_model("shop", "Order")
    for pk in Order.objects.filter(public_id__isnull=True).values_list("pk", flat=True).iterator():
        Order.objects.filter(pk=pk).update(public_id=uuid.uuid4())
    Order.objects.filter(paid=True).update(payment_status="paid")
    Order.objects.exclude(econt_shipment_num__isnull=True).exclude(econt_shipment_num="").update(
        shipment_status="created")
    # COD orders that already have a label were confirmed by the customer at the time
    Order.objects.filter(payment_method="cod", shipment_status="created").update(cod_confirmed_at=F("created_at"))


def check_duplicate_shipment_numbers(apps, schema_editor):
    from django.db.models import Count

    Order = apps.get_model("shop", "Order")
    dups = list(
        Order.objects.exclude(econt_shipment_num__isnull=True).exclude(econt_shipment_num="")
        .values("econt_shipment_num").annotate(n=Count("id")).filter(n__gt=1)
    )
    if dups:
        ids = {d["econt_shipment_num"]: list(
            Order.objects.filter(econt_shipment_num=d["econt_shipment_num"]).values_list("pk", flat=True))
            for d in dups}
        raise RuntimeError(
            "Cannot add the unique constraint on orders.econt_shipment_num: the same shipment number is stored on "
            f"several orders (shipment number -> order ids): {ids}. Resolve these manually (they are historical "
            "duplicates), then re-run migrate."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=120, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('open', 'open'), ('paid', 'paid'), ('expired', 'expired'), ('failed', 'failed'), ('superseded', 'superseded')], db_index=True, default='open', max_length=16)),
                ('checkout_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('started', 'started (no result recorded)'), ('created', 'created'), ('rejected', 'rejected by Econt (definitive)'), ('not_sent', 'request never reached Econt'), ('unknown', 'unknown - Econt may have created it')], db_index=True, default='started', max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shipment_num', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('request_summary', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('livemode', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'received'), ('processed', 'processed'), ('ignored', 'ignored'), ('rejected', 'rejected'), ('error', 'error')], default='received', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cod_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_cod_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_label_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='econt_receiver_pays_delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount_minor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Неплатена'), ('pending', 'Чака плащане'), ('paid', 'Платена'), ('failed', 'Неуспешно плащане')], db_index=True, default='unpaid', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),  # NO default: each row gets its own uuid in backfill()
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_apartment',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_entrance',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_floor',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_num',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('none', 'Няма заявка'), ('pending', 'Чака изпращане към Еконт'), ('in_progress', 'Изпраща се към Еконт'), ('created', 'Товарителница създадена'), ('failed', 'Грешка при Еконт'), ('unknown', 'Неясен резултат (проверка)')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(check_duplicate_shipment_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('econt_shipment_num__isnull', False), models.Q(('econt_shipment_num', ''), _negated=True)), fields=('econt_shipment_num',), name='uniq_order_econt_shipment_num'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shipment_status', 'created'), _negated=True), models.Q(('econt_shipment_num__isnull', False), models.Q(('econt_shipment_num', ''), _negated=True)), _connector='OR'), name='order_created_shipment_has_number'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.order'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='shop.order'),
        ),
        migrations.AddField(
            model_name='shipmentattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_attempts_log', to='shop.order'),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='shop.order'),
        ),
    ]
