# Generated by Django 5.2.17 on 2026-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_state_payments_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_other',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_quarter',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
