# Generated by Django 5.2.17 on 2026-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_receiver_quarter_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_bgn',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_bgn',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Цена (лв) - остаряло'),
        ),
    ]
