# Generated by Django 5.2.17 on 2026-10-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_eur_only_legacy_bgn_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='econt_status_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
